---
title: "Codebook template"
author: "Christa Smolarchuk"
date: "August 21, 2015"
output:
  html_document:
    keep_md: yes
---

## Project Description
This project contains summary data of each individual for each activity from the UCI HAR Dataset.The cleaned data set contains 40 observations from 30 subjects for different activities and measurements from 68 variables. 

##Study design and data processing
This project combined datasets from the UCI HAR Dataset which contained data for 30 subjects doing different activities. The variables in this dataset contain the mean measurement of each subject for each activity for each variable that initially measured a mean or standard deviation. 

###Collection of the raw data
The data was collected using an embedded gyroscope in a Samsung Galaxy SII that was worn on each subject's waist. The gyroscope collected measurements for 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz.

##Creating the tidy datafile
The dataset was downloaded from https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip. The data was opened and cleaned using RStudio version 0.99.467 to create dataset.txt

###Guide to create the tidy data file
1. Download the data
2. Open the data in R Studio
3. Apply variable labels and merge the datasets
4. Select variables containing measurements of a mean or standard deviation
5. Create a new variable containing the mean of each variable by activity type and subject ID

###Cleaning of the data
1. Data were downloaded, unzipped and read into R studio from the UCI HAR Dataset (https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip). 
2. Data were merged using using the dplyr package so that the data set contained a complete list of observations from the 30 subjects. 
3. Variables that did not include a label were then labelled. 
4. Data were then arranged in order based on subject ID and any duplicate columns in the data were removed. 
5. Measurement variables that contained a mean or standard deviation were selected and all other variables were dropped from the data using. 
6. Variables were renamed so that any short hand text was replaced with the complete word. 
7. Using the dplyr package the data were aggregated and measurment means were determined for each activity type of each individual. 
8. the complete data set was then saved as a text file. 

##Files included in the dataset
* dataset.txt - contains the data for the dataset
* Codebook.rmd - describes all of the variables
* run_analysis.R - containes the R script used to generated the dataset from the original data
* README.md - provides an overview of the dataset

##Description of the variables in the dataset.txt file

 * Subject_ID - ID of each subject in the study
 * Activity_ID - Activity Type
    1. Walking
    2. Walking Upstairs
    3. Walking Downstairs
    4. Sitting
    5. Standing
    6. Laying

These measurements are the means of the means for the following type of measurement: 
- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables
 * timeBodyAccelerometer-mean()-X    
 * timeBodyAccelerometer-mean()-Y            
 * timeBodyAccelerometer-mean()-Z      
 * timeGravityAccelerometer-mean()-X    
 * timeGravityAccelerometer-mean()-Y     
 * timeGravityAccelerometer-mean()-Z     
 * timeBodyAccelerometerJerk-mean()-X         
 * timeBodyAccelerometerJerk-mean()-Y    
 * timeBodyAccelerometerJerk-mean()-Z   
 * timeBodyGyroscope-mean()-X
 * timeBodyGyroscope-mean()-Y             
 * timeBodyGyroscope-mean()-Z      
 * timeBodyGyroscopeJerk-mean()-X   
 * timeBodyGyroscopeJerk-mean()-Y         
 * timeBodyGyroscopeJerk-mean()-Z 
 * timeBodyAccelerometerMagnitude-mean()    
 * timeGravityAccelerometerMagnitude-mean()
 * timeBodyAccelerometerJerkMagnitude-mean()     
 * timeBodyGyroscopeMagnitude-mean()       
 * timeBodyGyroscopeJerkMagnitude-mean()  
 * frequencyBodyAccelerometer-mean()-X 
 * frequencyBodyAccelerometer-mean()-Y 
 * frequencyBodyAccelerometer-mean()-Z    
 * frequencyBodyAccelerometerJerk-mean()-X 
 * frequencyBodyAccelerometerJerk-mean()-Y 
 * frequencyBodyAccelerometerJerk-mean()-Z 
 * frequencyBodyGyroscope-mean()-X 
 * frequencyBodyGyroscope-mean()-Y 
 * frequencyBodyGyroscope-mean()-Z  
 * frequencyBodyAccelerometerMagnitude-mean
 * frequencyBodyAccelerometerJerkMagnitude-mean
 * frequencyBodyGyroscopeMagnitude-mean
 * frequencyBodyGyroscopeJerkMagnitude-mean
 * timeBodyAccelerometer-std()-X  
 * timeBodyAccelerometer-std()-Y 
 * timeBodyAccelerometer-std()-Z 
 * timeGravityAccelerometer-std()-X   
 * timeGravityAccelerometer-std()-Y
 * timeGravityAccelerometer-std()-Z   
 * timeBodyAccelerometerJerk-std()-X
 * timeBodyAccelerometerJerk-std()-Y
 * timeBodyAccelerometerJerk-std()-Z
 * timeBodyGyroscope-std()-X
 * timeBodyGyroscope-std()-Y      
 * timeBodyGyroscope-std()-Z   
 * timeBodyGyroscopeJerk-std()-X 
 * timeBodyGyroscopeJerk-std()-Y
 * timeBodyGyroscopeJerk-std()-Z
 * timeBodyAccelerometerMagnitude-std()
 * timeGravityAccelerometerMagnitude-std()
 * timeBodyAccelerometerJerkMagnitude-std()
 * timeBodyGyroscopeMagnitude-std()
 * timeBodyGyroscopeJerkMagnitude-std()
 * frequencyBodyAccelerometer-std()-X
 * frequencyBodyAccelerometer-std()-Y
 * frequencyBodyAccelerometer-std()-Z
 * frequencyBodyAccelerometerJerk-std()-X
 * frequencyBodyAccelerometerJerk-std()-Y
 * frequencyBodyAccelerometerJerk-std()-Z
 * frequencyBodyGyroscope-std()-X
 * frequencyBodyGyroscope-std()-Y
 * frequencyBodyGyroscope-std()-Z
 * frequencyBodyAccelerometerMagnitude-std
 * frequencyBodyAccelerometerJerkMagnitude-std
 * frequencyBodyGyroscopeMagnitude-std        
 * frequencyBodyGyroscopeJerkMagnitude-std  



